### ISSUE TITLE
4 numbers on a line

### ISSUE THREAD

**Issue by jacksonbrant** [dennis-classes/se2832-lab-01-isosceles-BlackbeardMatt#2]
4 numbers on a line prints something like "The triangle 4 5 6 7 is a valid triangle. The triangle is a scalene triangle."

**Comment by BlackbeardMatt** [comment]
3.0 2.0 4.0 5.0 # Testing 4 numbers

Prints

The triangle 2.0 3.0 4.0 is a valid triangle. The triangle is a scalene triangle.
