### ISSUE TITLE
Triangles with one very long side

### ISSUE THREAD

**Issue by jacksonbrant** [dennis-classes/se2832-lab-01-isosceles-BlackbeardMatt#4]
If a triangle has one side longer than the other 2, it is said to be valid

**Comment by BlackbeardMatt** [comment]
Checked with multiple inputs

The triangle 15.0 5.0 5.0 is not a valid triangle. 
The triangle 5.0 15.0 5.0 is not a valid triangle. 
The triangle 5.0 5.0 15.0 is not a valid triangle. 
The triangle 3.0 2.0 500000000.0 is not a valid triangle.
